### PR TITLE
Updating event details

### PR DESCRIPTION
**Pull request by SMBuilt**

### CODE REVIEW

**Comment by BarryThePenguin** [comment]
Looks like `node-sass` causing issues :(

**Comment by SMBuilt** [comment]
I knew there was a reason I ignored the package-lock last commit. Hopefully that works.

**Comment by SMBuilt** [comment]
:(

**Comment by BarryThePenguin** [comment]
I think it was the node version that was the issue... Was using node@10

I've set it to use node@8 for now

**Comment by SMBuilt** [comment]
Awesome, thanks for looking into it.

**Pull request merged**
